version: '3.7'

services:
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./cert/linkssky.p12:/etc/prometheus/linkssky.p12
      - ./cert/linkssky.cert:/etc/prometheus/linkssky.cert
      - ./cert/linkssky.key:/etc/prometheus/linkssky.key
    user: 'root'
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring: